### PR TITLE
Remove Console Log

### PR DESCRIPTION
**Pull request by IchiiSama**
You should remove the console.log with all the coordinates at line 96. It isn't useful to debug this on the released package

### CODE REVIEW

**Comment by Shashank3736** [comment]
Thx man while testing i completely forget to remove console.log() from master branch and released it.

**Comment by IchiiSama** [comment]
No problem, I tested the package last night and saw that it was here, I removed it in my node_modules but I thought it would be best to make a pull request

**Comment by Shashank3736** [comment]
tonight at 7 pm IST means around 6 hours after this nsg

**Comment by Shashank3736** [comment]
@all-contributors please add @IchiiDev For reporting and solving console.log() debug error

**Comment by Shashank3736** [comment]
@all-contributors please add @IchiiDev for bug report

**Pull request merged**
