### PR TITLE
Fixing typings declaration and add example in typescript

### PR DESCRIPTION
**Pull request by skymunn**
I was make a bot Discord using TypeScript language, and this typings for package didn't recognize in my Text Editor (i using Visual Studio Code). So, I tried to help fix this package by fixing the existing typing so that a Text Editor like Visual Studio Code can recognize this package well.

### CODE REVIEW

**Comment by Shashank3736** [comment]
You tested typings now after these changes

**Comment by skymunn** [comment]
image
Yeah, i've just test it and it works.

**Comment by Shashank3736** [comment]
Thx for your contribution in typings/doc.

**Comment by Shashank3736** [comment]
@all-contributors please add @skymunn for doc and code

**Pull request merged**
